// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysuqbjwqsyidqyrqurmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzdXFiandxc3lpZHF5cnF1cm1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzQ0ODIsImV4cCI6MjA3MzYxMDQ4Mn0.-gBW9dp5w45M_rRD3S2Tk8urLU8tlq8v2chbaUH1byM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});